### ISSUE TITLE
Nametable/attribute table offset on hover

### ISSUE THREAD

**Issue by kzurawel** [jpwhiting/nestool#2]
I love the concept of a cross-platform NES Screen Tool, thanks so much for all of your work on this. It's just missing one feature from NES Screen Tool that I use regularly: the ability to hover over the left-side nametable view and see in the bottom status bar the nametable offset and controlling attribute table offset for what's being hovered over.

Is it possible to get this information somewhere else in the app and I'm just missing it? Would this be a simple addition?

Thanks!

**Comment by jpwhiting** [comment]
I think that would be pretty quick to add. I'll not likely get it added this week though, feel free to take a stab at it if you are inclined, otherwise I'll get to it when I can.

**Comment by kzurawel** [comment]
Gave it a try:   https://github.com/jpwhiting/nestool/pull/3
